//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class abrechnung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abrechnung()
        {
            this.produktegruppes = new HashSet<produktegruppe>();
            this.softwaredienstleistungs = new HashSet<softwaredienstleistung>();
        }
    
        public long abrechnung_id { get; set; }
        public long kundenkonto_fk { get; set; }
        public long location_fk { get; set; }
        public long device_fk { get; set; }
        public long interface_fk { get; set; }
    
        public virtual kundenkonto kundenkonto { get; set; }
        public virtual location location { get; set; }
        public virtual device device { get; set; }
        public virtual @interface @interface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produktegruppe> produktegruppes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<softwaredienstleistung> softwaredienstleistungs { get; set; }
    }
}
