//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.pointofdeliveries = new HashSet<pointofdelivery>();
        }
    
        public long customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string addressnumber { get; set; }
        public long kundenkonto_fk { get; set; }
        public string tel { get; set; }
        public string eMail { get; set; }
        public string url { get; set; }
        public string password { get; set; }
    
        public virtual kundenkonto kundenkonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pointofdelivery> pointofdeliveries { get; set; }
    }
}
