//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long log_id { get; set; }
        public long device_fk { get; set; }
        public System.DateTime timestamp { get; set; }
        public string logMessage { get; set; }
        public string level { get; set; }
        public Nullable<short> is_acknowledged { get; set; }
    
        public virtual device device { get; set; }
    }
}
