//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget
{
    using System;
    using System.Collections.Generic;
    
    public partial class pointofdelivery
    {
        public long pod_id { get; set; }
        public long customer_id_fk { get; set; }
        public long contact_id_fk { get; set; }
        public long location_fk { get; set; }
        public string designation { get; set; }
        public System.TimeSpan timezone { get; set; }
        public short timeZonePositiv { get; set; }
        public string ntpServerIp { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual customer customer { get; set; }
        public virtual location location { get; set; }
    }
}
