//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget
{
    using System;
    using System.Collections.Generic;
    
    public partial class produktegruppe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produktegruppe()
        {
            this.produktes = new HashSet<produkte>();
        }
    
        public int produktegruppe_id { get; set; }
        public string hardware { get; set; }
        public string software { get; set; }
        public string sonstigeArtikel { get; set; }
        public long abrechung_fk { get; set; }
    
        public virtual abrechnung abrechnung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produkte> produktes { get; set; }
    }
}
