//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlNugget
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkte
    {
        public int artikelnummer_id { get; set; }
        public string artikelname { get; set; }
        public float preis { get; set; }
        public int produktegruppe_fk { get; set; }
    
        public virtual produktegruppe produktegruppe { get; set; }
    }
}
